config/routes.rb
Rails.application.routes.draw do
  namespace :user do
    get 'bookmarks/create'
    get 'bookmarks/destroy'
  end
  devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope module: :user do
    root to: 'homes#top'
    resources :contents, only:[:index, :show, :edit, :new, :create, :destroy, :update]
    resources :contents do
      resource :favorites, only: [:create, :destroy]
      resource :bookmarks, only: [:create, :destroy]
    end
    resources :users, only:[:index, :show, :edit, :update]
    get 'users/unsubscribe/:id' => 'users#unsubscribe', as: 'unsubscribe'
    patch 'users/unsubscribe' => 'users#destroy', as: 'destroy'
    resources :contacts, only: [:new, :create]
    post 'contacts/confirm' => 'contacts#confirm', as: 'confirm'
    post 'contacts/back' => 'contacts#back', as: 'back'
    get 'thanks', to: 'contacts#thanks', as: 'thanks'
  end

  namespace :admin do
    get '/' => 'homes#top'
    resources :contents, only:[:index, :show, :edit, :destroy, :update]
    resources :genres, only:[:index, :create, :edit, :destroy, :update]
    resources :users, only:[:index, :show, :edit, :update]
  end
end

app/models/content.rb
class Content < ApplicationRecord
  # 住所を緯度経度に変換する。
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  enum review: { "1": 1 ,"2": 2 ,"3": 3 ,"4": 4 ,"5": 5 }

  validates :name, presence: true
  validates :address, presence: true

  belongs_to :genre
  belongs_to :user
  # いいね機能のアソシエーション
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  # ブックマーク機能のアソシエーション
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_users, through: :bookmarks, source: :user

  attachment :content_image

  def favorited_by?(current_user)
    favorites.where(user_id: current_user.id).exists?
  end

  def bookmarked_by?(current_user)
    bookmarks.where(user_id: current_user.id).exists?
  end
end

app/controllers/admin/contents_controller.rb
class Admin::ContentsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @contents = Content.all.order(created_at: :desc)
  end

  def show
    @content = Content.find(params[:id])
  end

  def edit
    @content = Content.find(params[:id])
  end

  def destroy
    @content = Content.find(params[:id])
    if @content.destroy
      redirect_to admin_contents_path, notice: '投稿を削除しました'
    else
      flash.now[:alert] = '投稿の削除に失敗しました'
      render :edit
    end
  end

  def update
    @content = Content.find(params[:id])
    if @content.update(content_params)
      redirect_to admin_content_path(@content.id), notice: '投稿の編集が完了しました'
    else
      flash.now[:alert] = '投稿の編集に失敗しました'
      render :edit
    end
  end

  private

  def content_params
    params.require(:content).permit(:user_id, :genre_id, :name, :address, :introduction, :latitude, :longitude, :image, :review)
  end
end

app/controllers/user/contents_controller.rb
class User::ContentsController < ApplicationController
  before_action :authenticate_user!

  def index
    @contents = Content.order("created_at desc")
  end

  def show
    @content = Content.find(params[:id])
  end

  def edit
    @content = Content.find(params[:id])
  end

  def new
    @content = Content.new
    @genres = Genre.all
  end

  def create
    @content = Content.new(content_params)
    if @content.save
      redirect_to content_path(@content.id), notice: '投稿が完了しました'
    else
      flash.now[:alert] = '投稿内容を確認してください'
      render :new
    end
  end

  def destroy
    @content = Content.find(params[:id])
    if current_user.id == @content.user.id
      @content.destroy
      redirect_to contents_path, notice: '投稿を削除しました。'
    else
      flash.now[:alert] = '投稿を削除できませんでした'
      render :edit
    end
  end

  def update
    @content = Content.find(params[:id])
    if current_user.id == @content.user.id
      @content.update(content_params)
      redirect_to content_path(@content.id), notice: '投稿の編集が完了しました！'
    else
      flash.now[:alert] = '投稿の編集に失敗しました'
      render :edit
    end
  end

  private

  def content_params
    params.require(:content).permit(:user_id, :genre_id, :name, :address, :introduction, :latitude, :longitude, :content_image, :review)
  end
end

app/helpers/admin/contents_helper.rb
module Admin::ContentsHelper
end

app/helpers/user/contents_helper.rb
module User::ContentsHelper
end

app/views/admin/contents/edit.html.erb
<%= form_with model: @content, :url => {:action => :update}, local:true do |f| %>
<div class="container-lg-fluid">
  <div class="row text-center mx-auto" style="width: 80%;">
    <table class="col-lg table table-bordered mx-auto my-3">
      <thead>
      </thead>
      <tbody>
        <tr>
          <th>ジャンル</th>
          <td class="form-group">
            <%= f.collection_select(:genre_id, Genre.all, :id, :name, autofocus: true ) %>
          </td>
        </tr>
        <tr>
          <th>キャンプ場名</th>
          <td class="form-group">
            <%= f.text_field :name,value: @content.name, class: "form-control" %>
          </td>
        </tr>
        <tr>
          <th>住所</th>
          <td class="form-group">
            <%= f.text_field :address,value: @content.address, class: "form-control" %>
          </td>
        </tr>
        <tr>
          <th>紹介文</th>
          <td class="form-group">
            <%= f.text_field :introduction,value: @content.introduction, class: "form-control" %>
          </td>
        </tr>
        <tr>
          <th>評価</th>
          <td class="form-group">
            <%= f.select :review, Content.reviews.keys, {prompt: "選択してください"} %>
          </td>
        </tr>
        <tr>
          <th>写真</th>
          <td class="form-group">
            <%= f.attachment_field :content_image, class: "form-control-file" %>
          </td>
        </tr>
        <tr>
          <td colspan="2" class="form-group">
            <%= f.submit '編集内容を保存', class: "btn btn-success mr-3" %>
            <%= link_to "投稿を削除", admin_content_path, method: :delete, class: "btn btn-danger ml-3" %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
<% end %>

app/views/admin/contents/index.html.erb
<div class="container-lg">
  <h2 class="mt-3">投稿一覧</h2>
  <div class="row align-items-center">
    <table class="col-lg table table-bordered mx-auto">
      <thead>
        <tr>
          <th style="width: 100px;">日時</th>
          <th style="width: 100px;">名前</th>
          <th style="width: 100px;">キャンプ場名</th>
          <th style="width: 150px;">住所</th>
        </tr>
      </thead>
      <tbody>
        <% if @search_contents %>
            <% @search_contents.first(20).each do |content| %>
              <tr>
                <td><%= content.created_at.strftime("%Y/%m/%d %H:%M:%S") %></td>
                <td>
                  <%= content.user.name %>
                </td>
                <td>
                  <%= link_to admin_content_path(content.id) do %>
                    <%= content.name %>
                  <% end %>
                </td>
                <td><%= content.address %></td>
              </tr>
            <% end %>
          <% else %>
            <% @contents.first(20).each do |content| %>
              <tr>
                <td><%= content.created_at.strftime("%Y/%m/%d %H:%M:%S") %></td>
                <td>
                  <%= content.user.name %>
                </td>
                <td>
                  <%= link_to admin_content_path(content.id) do %>
                    <%= content.name %>
                  <% end %>
                </td>
                <td><%= content.address %></td>
              </tr>
            <% end %>
          <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/contents/show.html.erb
<div class="container-lg">
  <h2 class="mt-3"><%= @content.name %></h2>
  <div class="row">
    <table class="col-lg table table-bordered mx-auto my-3">
      <thead>
      </thead>
      <tbody>
        <tr>
          <td style="width: 20%;">評価</td>
          <td>
            <%= @content.review %>
          </td>
          <td rowspan="5" class="text-center">
            <%= attachment_image_tag @content, :content_image, :fill, 250, 250, size:'250x250', format: 'jpeg', fallback: "no_image.jpeg" %>
          </td>
        </tr>
        <tr>
          <td>ジャンル</td>
          <td>
            <%= @content.genre.name %>
          </td>
        </tr>
        <tr>
          <td>住所</td>
          <td><%= @content.address %></td>
        </tr>
        <tr>
          <td>紹介文</td>
          <td><%= @content.introduction %></td>
        </tr>
        <tr>
          <td colspan="2" class="text-center">
            <%= link_to "編集する", edit_admin_content_path(@content.id), class: "btn btn-success mr-3", type:"button" %>
            <%= link_to "投稿を削除", admin_content_path, method: :delete, class: "btn btn-danger ml-3", type:"button" %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
<div id="map"></div>
<script type="text/javascript">
  function initMap() {
// latitude,longitudeから位置を特定
    var point ={lat: <%= @content.latitude %>, lng: <%= @content.longitude %>};
    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 15,
      center: point
      });
    var transitLayer = new google.maps.TransitLayer();
    transitLayer.setMap(map);

    var contentString = '住所：<%= @content.address %>';
    var infowindow = new google.maps.InfoWindow({
      content: contentString
    });

// Map上の指定した位置にピンを挿して表示する
    var marker = new google.maps.Marker({
      position:point,
      map: map,
      title: contentString
    });

    marker.addListener('click', function() {
      infowindow.open(map, marker);
    });
  }
</script>
<!-- googlemap API -->
<script async defer
  src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap">
</script>