config/routes.rb
Rails.application.routes.draw do
  namespace :user do
    get 'bookmarks/create'
    get 'bookmarks/destroy'
  end
  devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope module: :user do
    root to: 'homes#top'
    resources :contents, only:[:index, :show, :edit, :new, :create, :destroy, :update]
    resources :contents do
      resource :favorites, only: [:create, :destroy]
      resource :bookmarks, only: [:create, :destroy]
    end
    resources :users, only:[:index, :show, :edit, :update]
    get 'users/unsubscribe/:id' => 'users#unsubscribe', as: 'unsubscribe'
    patch 'users/unsubscribe' => 'users#destroy', as: 'destroy'
    resources :contacts, only: [:new, :create]
    post 'contacts/confirm' => 'contacts#confirm', as: 'confirm'
    post 'contacts/back' => 'contacts#back', as: 'back'
    get 'thanks', to: 'contacts#thanks', as: 'thanks'
  end

  namespace :admin do
    get '/' => 'homes#top'
    resources :contents, only:[:index, :show, :edit, :destroy, :update]
    resources :genres, only:[:index, :create, :edit, :destroy, :update]
    resources :users, only:[:index, :show, :edit, :update]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, uniqueness: true, length: { minimum: 2,maximum: 10 }
  validates :email, presence: true, uniqueness: true

  has_many :genres, through: :contents
  has_many :contents, through: :favorites
  # いいね機能のアソシエーション
  has_many :favorites, dependent: :destroy
  has_many :favorite_contents, through: :favorites, source: :item
  has_many :goods, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :contacts, dependent: :destroy

  attachment :image

  enum is_active: { 有効: true, 無効: false }

  # 有効のユーザーしかログインできなくする
  def active_for_authentication?
    super && (self.is_active == "有効")
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all
  end

  def show
    id = params[:id]
    @user = User.find(params[:id])
    @contents = Content.where("user_id = #{id}")
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user.id), notice: '編集が完了しました'
    else
      flash.now[:alert] = '編集に失敗しました'
      render :edit
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :introduction, :image, :is_active)
    end
end

app/controllers/user/bookmarks_controller.rb
class User::BookmarksController < ApplicationController
  
  before_action :authenticate_user!
  before_action :set_bookmark

  def create
    @content = Content.find(params[:content_id])
    @bookmark = current_user.bookmarks.build(content_id: params[:content_id])
    @bookmark.save
  end

  def destroy
    @content = Content.find(params[:content_id])
    @bookmark = current_user.bookmarks.find_by(content_id: @content.id)
    @bookmark.destroy
  end

  private
  def set_bookmark
    @content = Content.find(params[:content_id])
  end
end

app/controllers/user/contacts_controller.rb
class User::ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  # newアクションから入力内容を受け取り、
  # 送信ボタンを押されたらcreateアクションを実行します。
  def confirm
    @contact = Contact.new(params[:contact].permit( :name, :email, :phone_number, :subject, :message))
    if @contact.valid?
      # OK。確認画面を表示
      render :action => 'confirm'
    else
      # NG。入力画面を再表示
      flash.now[:alert] = '入力内容を確認してください'
      render :action => 'new'
    end
  end

  # backアクション
  # 入力内容を保持したまま前のページに戻る
  def back
    @contact = Contact.new(contact_params)
    render :new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      # メールを送信する（今回は行わない）
      # ContactMailer.send_mail(@contact).deliver_now
      redirect_to thanks_path
    else
      flash.now[:alert] = '送信に失敗しました'
      render :new
    end
  end

  def thanks
  end

  private

  def contact_params
    params.require(:contact).permit( :name, :email, :phone_number, :subject, :message )
  end
end

app/controllers/user/contents_controller.rb
class User::ContentsController < ApplicationController
  before_action :authenticate_user!

  def index
    @contents = Content.order("created_at desc")
  end

  def show
    @content = Content.find(params[:id])
  end

  def edit
    @content = Content.find(params[:id])
  end

  def new
    @content = Content.new
    @genres = Genre.all
  end

  def create
    @content = Content.new(content_params)
    if @content.save
      redirect_to content_path(@content.id), notice: '投稿が完了しました'
    else
      flash.now[:alert] = '投稿内容を確認してください'
      render :new
    end
  end

  def destroy
    @content = Content.find(params[:id])
    if current_user.id == @content.user.id
      @content.destroy
      redirect_to contents_path, notice: '投稿を削除しました。'
    else
      flash.now[:alert] = '投稿を削除できませんでした'
      render :edit
    end
  end

  def update
    @content = Content.find(params[:id])
    if current_user.id == @content.user.id
      @content.update(content_params)
      redirect_to content_path(@content.id), notice: '投稿の編集が完了しました！'
    else
      flash.now[:alert] = '投稿の編集に失敗しました'
      render :edit
    end
  end

  private

  def content_params
    params.require(:content).permit(:user_id, :genre_id, :name, :address, :introduction, :latitude, :longitude, :content_image, :review)
  end
end

app/controllers/user/favorites_controller.rb
class User::FavoritesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_favorite

  def create
    @content = Content.find(params[:content_id])
    @favorite = current_user.favorites.build(content_id: params[:content_id])
    @favorite.save
  end

  def destroy
    @content = Content.find(params[:content_id])
    @favorite = current_user.favorites.find_by(content_id: @content.id)
    @favorite.destroy
  end

  private
  def set_favorite
    @content = Content.find(params[:content_id])
  end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController

  def top
    @contents = Content.all
  end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    id = params[:id]
    @user = User.find(params[:id])
    @contents = Content.where("user_id = #{id}")
    @bookmarks = Bookmark.where(user_id: current_user.id)
  end

  def edit
    @user = User.find(current_user.id)
  end

  def update
    @user = User.find(current_user.id)
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: '編集が完了しました！'
    else
      flash.now[:alert] = '編集内容を確認してください'
      render :edit
    end
  end

  def unsubscribe
    @user = User.find(current_user.id)
  end

  def destroy
    @user = User.find(current_user.id)
    if @user.update(is_active: "無効")
      reset_session
      redirect_to root_path, notice: '退会が完了しました。ご利用ありがとうございました'
    else
      flash.now[:alert] = '退会が正常に行われませんでした'
      render :unsubscribe
    end
  end

    private
  def user_params
    params.require(:user).permit(:name, :introduction, :image, :is_active)
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user/bookmarks_helper.rb
module User::BookmarksHelper
end

app/helpers/user/contacts_helper.rb
module User::ContactsHelper
end

app/helpers/user/contents_helper.rb
module User::ContentsHelper
end

app/helpers/user/favorites_helper.rb
module User::FavoritesHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/views/admin/users/edit.html.erb
<%= form_with model: @user,:url => {:action => :update}, local:true do |f| %>
  <div class="container-lg-fluid" style="background-color: rgba(255,250,220,1.0);">
    <div class="row text-center mx-auto" style="width: 80%;">
      <table class="col-lg table table-bordered mx-auto my-3">
        <thead>
        </thead>
        <tbody>
          <tr>
            <th>ニックネーム</th>
            <td class="form-group">
              <%= f.text_field :name, autofocus: true, class: "form-control" %>
            </td>
          </tr>
          <tr>
            <th>写真</th>
            <td class="form-group">
              <%= f.attachment_field :image, class: "form-control-file" %>
            </td>
          </tr>
          <tr>
            <th>メールアドレス</th>
            <td class="form-group">
              <%= f.text_field :email, autofocus: true, class: "form-control" %>
            </td>
          </tr>
          <tr>
            <th>紹介文</th>
            <td class="form-group">
              <%= f.text_area :introduction, autofocus: true, class: "form-control" %>
            </td>
          </tr>
          <tr class="form-group">
            <th>会員ステータス</th>
            <td>
              <%= f.radio_button :is_active, "有効" %>
              <%= f.label :is_active, "有効", {value: :is_active, style: "display: inline-block;"} %>
              <%= f.radio_button :is_active, "無効" %>
              <%= f.label :is_active, "無効", {value: :is_active, style: "display: inline-block;"} %>
            </td>
          </tr>
          <tr>
            <th></th>
            <td class="form-group">
              <%= f.submit '編集内容を保存', class: "btn btn-success" %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
<% end %>

app/views/admin/users/index.html.erb
<div class="container-lg">
  <h2 class="mt-3">会員一覧</h2>
  <div class="row mx-auto">
    <table class="col-lg table table-bordered mx-auto">
      <thead>
        <tr>
          <th>ID</th>
          <th>名前</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
        <tr>
          <th><%= user.id %></td>
          <td><%= link_to user.name, admin_user_path(user.id) %></td>
          <td><%= user.email %></td>
          <td><%= user.is_active %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container-lg-fluid">
  <h3 class="pt-3 text-center">マイページ</h3>
  <div class="row mx-auto" style="width: 80%;">
    <table class="col-lg table table-bordered mx-auto my-3">
      <thead>
      </thead>
      <tbody>
        <tr>
          <td rowspan="4" class="lg text-center" style="width: 350px;">
            <%= attachment_image_tag @user, :image, :fill, 300, 300, size:'300x300', format: 'jpeg', fallback: "no_image.jpeg" %>
          </td>
          <td>ニックネーム</td>
          <td><%= @user.name %></td>
        </tr>
        <tr>
          <td>紹介文</td>
          <td><%= @user.introduction %></td>
        </tr>
        <tr>
          <td>メールアドレス</td>
          <td><%= @user.email %></td>
        </tr>
        <tr>
          <td>会員ステータス</td>
          <td><%= @user.is_active %></td>
        </tr>
        <tr>
          <td colspan="3" class="text-center">
            <%= link_to "編集する", edit_admin_user_path(@user.id), class: "btn btn-success", type:"button" %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  <h3 class="mt-3 text-center">投稿リスト</h3>
  <div class="row text-center mx-auto" style="width: 80%;">
    <table class="col-lg table table-bordered mx-auto my-3">
      <thead>
        <th>キャンプ場名</th>
        <th>住所</th>
        <th>紹介文</th>
        <th>評価</th>
      </thead>
      <tbody>
        <% @contents.each do |content| %>
        <tr>
          <td>
            <%= link_to admin_content_path(content.id) do %>
              <%= content.name %>
            <% end %>
            </td>
          <td><%= content.address %></td>
          <td><%= content.introduction %></td>
          <td><%= content.review %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>